"""
Triangular, pentagonal, and hexagonal
-------------------------------------

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from utils.timer import time_it
from utils.sequences import hexagonal_numbers, is_pentagonal

#-------------------------------------------------------------------------------------------------

@time_it
def problem_45():

    # We can ignore the triangle number aspect of the problem altogether, since all hexagonal
    # numbers are also triangular numbers

    # get an iterator for hexagonal numbers, and skip them up to 40755, since we want to identify
    # a number after that point
    hexagonals = hexagonal_numbers()
    while next(hexagonals) < 40755:
        pass

    for n in hexagonals:
        if is_pentagonal(n):
            print(n)
            break

#-------------------------------------------------------------------------------------------------

if __name__ == '__main__':
    problem_45()
